### ISSUE TITLE
Resort Area warp points

### ISSUE THREAD

**Issue by Imeryl** [shmove/LeahsPlatinumTracker#2]
Using pointcrows randomiser there are 2 warp points in the resort area that aren't currently markable. I've tried to open the project locally to see if I could make the adjustments and PR them but I didn't manage to get it working locally.

**Comment by shmove** [comment]
I believe these warps were not randomised in earlier versions, I will add those in a patch as soon as I can.

**Comment by shmove** [comment]
Fixed in https://github.com/shmove/LeahsPlatinumTracker/commit/f9c78dc22ad74f1e35397b274fd83d0f3a501b45. App should auto-request an update on launch.

**Comment by Imeryl** [comment]
Thanks a lot! Love the program btw
